.TH decode 1 "13 June 2017" "1.0" "decode man page"

.SH NAME
decode - decode Psychic CAPtures (PCAP's) of Zerg communications

.SH SYNOPSIS
.B decode [
.I FILES
.B ]

.SH DESCRIPTION
This manual documents the
.B decode(1)
tool.
.B decode
takes a .pcap capture file and prints a human-readable version to stdout.

.SH AUTHOR
Written by Josh Abraham.

.SH REPORTING BUGS
Help at https://github.com/jabedude/

.SH COPYRIGHT
Copyright (c) 2017 Joshua Abraham MIT License
