.TH encode 1 "13 June 2017" "1.0" "encode man page"

.SH NAME
encode - encode Psychic CAPtures (PCAP's) of Zerg communications

.SH SYNOPSIS
.B encode [
.I FILE TO BE ENCODED
.B ]
...
.B [
.I PCAP DESTINATION FILE
.B ]

.SH DESCRIPTION
This manual documents the
.B encode(1)
tool.
.B encode
takes a text file and converts it to a .pcap Psychic Capture.

.SH AUTHOR
Written by Josh Abraham.

.SH REPORTING BUGS
Help at https://github.com/jabedude/

.SH COPYRIGHT
Copyright (c) 2017 Joshua Abraham MIT License
